### PR TITLE
Use GH Actions instead of Travis CI

### PR DESCRIPTION
**Pull request by aahlenst**
See https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1668.

### CODE REVIEW

**Comment by cilki** [comment]
Thanks for the PR. I've never used GitHub actions before, but I should be able to figure it out in the repo settings.

One thing is that the test job should also run on Windows and macOS. Although we'd never deploy to those platforms, the tests do an additional sanity check by running `java -version` on the runtimes according to platform.

There's also a usage of `TRAVIS_OS_NAME` which drives the platform detection that needs to change to the GitHub actions equivalent.

Thanks again 👍

**Comment by aahlenst** [comment]
> One thing is that the test job should also run on Windows and macOS. Although we'd never deploy to those platforms, the tests do an additional sanity check by running java -version on the runtimes according to platform.

For some reasons, I get failures on Windows and macOS. Haven't yet figured out what the problem is.

**Comment by aahlenst** [comment]
Ah. Totally missed `TRAVIS_OS_NAME`. Maybe that's the reason of the failure.

**Comment by cilki** [comment]
Yeah, it will assume Linux if `TRAVIS_OS_NAME` isn't set and download the wrong jlink binary.

**Review by karianna — APPROVED** [review]
LGTM

**Comment by aahlenst** [comment]
@cilki Please take another look.

I've dropped `TRAVIS_OS_NAME` and I'm using `runtime.GOOS` to determine the local platform. Has the advantage that it just works on any platform, not only Linux. As a result, I could enable testing on macOS. Windows is broken because of #22.

**Comment by cilki** [comment]
I'm happy with this. I'll take a look at the Windows issue today and we can add it to the test matrix when fixed.

Thanks!

**Pull request merged**
